
from pygments.lexer import RegexLexer, include, bygroups, words, combined, inherit
from pygments.token import (
    Keyword,
    Literal,
    Name,
    Comment,
    String,
    Number,
    Operator,
    Whitespace,
    Punctuation,
)
from pygments.lexers.graphics import GLShaderLexer

__all__ = ["GDShaderLexer"]

KEYWORDS = (
    "shader_type",
    "render_mode",

    # Uniform hints.
    "source_color",
    "hint_enum",
    "hint_range",
    "hint_normal",
    "hint_default_white",
    "hint_default_black",
    "hint_default_transparent",
    "hint_anisotropy",
    "hint_roughness_r",
    "hint_roughness_g",
    "hint_roughness_b",
    "hint_roughness_a",
    "hint_roughness_normal",
    "hint_roughness_gray",
    "filter_nearest",
    "filter_nearest_mipmap",
    "filter_nearest_mipmap_anisotropic",
    "filter_linear",
    "filter_linear_mipmap",
    "filter_linear_mipmap_anisotropic",
    "repeat_enable",
    "repeat_disable",
    "hint_screen_texture",
    "hint_depth_texture",
    "hint_normal_roughness_texture",
    "no_editor",
    "no_storage",

    # Data types.
    "samplerExternalOES",

    # Other.
    "group_uniforms",
    "global",
    "instance",
)
KEYWORDS_CONTROL_FLOW = (
    "break",
    "case"
    "continue",
    "do",
    "elif",
    "else",
    "for",
    "if",
    "return",
    "switch",
    "while",
)
BUILT_IN_SPATIAL_GLOBAL = (
    "TIME",
    "PI",
    "TAU",
    "E",
    "OUTPUT_IS_SRGB",
    "CLIP_SPACE_FAR",
    "IS_MULTIVIEW",
    "IN_SHADOW_PASS",
)
BUILT_IN_SPATIAL_VERTEX = (
    "VIEWPORT_SIZE",
    "VIEW_MATRIX",
    "INV_VIEW_MATRIX",
    "MAIN_CAM_INV_VIEW_MATRIX",
    "INV_PROJECTION_MATRIX",
    "NODE_POSITION_WORLD",
    "NODE_POSITION_VIEW",
    "CAMERA_POSITION_WORLD",
    "CAMERA_DIRECTION_WORLD",
    "CAMERA_VISIBLE_LAYERS",
    "INSTANCE_ID",
    "INSTANCE_CUSTOM",
    "VIEW_INDEX",
    "VIEW_MONO_LEFT",
    "VIEW_RIGHT",
    "EYE_OFFSET",
    "VERTEX",
    "VERTEX_ID",
    "NORMAL",
    "TANGENT",
    "BINORMAL",
    "POSITION",
    "UV",
    "UV2",
    "COLOR",
    "ROUGHNESS",
    "POINT_SIZE",
    "MODELVIEW_MATRIX",
    "MODELVIEW_NORMAL_MATRIX",
    "MODEL_MATRIX",
    "MODEL_NORMAL_MATRIX",
    "PROJECTION_MATRIX",
    "BONE_INDICES",
    "BONE_WEIGHTS",
    "CUSTOM0",
    "CUSTOM1",
    "CUSTOM2",
    "CUSTOM3",
    "Z_CLIP_SCALE",
)
BUILT_IN_SPATIAL_FRAGMENT = (
    "VIEWPORT_SIZE",
    "FRAGCOORD",
    "FRONT_FACING",
    "VIEW",
    "UV",
    "UV2",
    "COLOR",
    "POINT_COORD",
    "MODEL_MATRIX",
    "MODEL_NORMAL_MATRIX",
    "VIEW_MATRIX"
    "INV_VIEW_MATRIX"
    "PROJECTION_MATRIX",
    "INV_PROJECTION_MATRIX",
    "NODE_POSITION_WORLD",
    "NODE_POSITION_VIEW",
    "CAMERA_POSITION_WORLD",
    "CAMERA_DIRECTION_WORLD",
    "CAMERA_VISIBLE_LAYERS",
    "VERTEX",
    "LIGHT_VERTEX",
    "VIEW_INDEX",
    "VIEW_MONO_LEFT",
    "VIEW_RIGHT",
    "EYE_OFFSET",
    "SCREEN_TEXTURE",
    "SCREEN_UV",
    "DEPTH_TEXTURE",
    "DEPTH",
    "NORMAL",
    "TANGENT",
    "BINORMAL",
    "NORMAL_MAP",
    "NORMAL_MAP_DEPTH",
    "BENT_NORMAL_MAP",
    "ALBEDO",
    "ALPHA",
    "ALPHA_SCISSOR_THRESHOLD",
    "ALPHA_HASH_SCALE",
    "ALPHA_ANTIALIASING_EDGE",
    "ALPHA_TEXTURE_COORDINATE",
    "PREMUL_ALPHA_FACTOR",
    "METALLIC",
    "SPECULAR",
    "ROUGHNESS",
    "RIM_TINT",
    "CLEARCOAT",
    "CLEARCOAT_GLOSS",
    "ANISOTROPY",
    "ANISOTROPY_FLOW",
    "SSS_STRENGTH",
    "SSS_TRANSMITTANCE_DEPTH",
    "SSS_TRANSMITTANCE_BOOST",
    "BACKLIGHT",
    "AO",
    "AO_LIGHT_AFFECT",
    "FOG",
    "RADIANCE",
    "IRRADIANCE",
)
BUILT_IN_SPATIAL_LIGHT = (
    "VIEWPORT_SIZE",
    "FRAGCOORD",
    "MODEL_MATRIX",
    "INV_MODEL_MATRIX",
    "VIEW_MATRIX",
    "PROJECTION_MATRIX",
    "INV_PROJECTION_MATRIX",
    "NORMAL",
    "SCREEN_UV",
    "UV",
    "UV2",
    "VIEW",
    "LIGHT",
    "LIGHT_COLOR",
    "SPECULAR_AMOUNT",
    "LIGHT_IS_DIRECTIONAL",
    "ATTENUATION",
    "ALBEDO",
    "BACKLIGHT",
    "METALLIC",
    "ROUGHNESS",
    "DIFFUSE_LIGHT",
    "SPECULAR_LIGHT",
    "ALPHA",
)
BUILT_IN_FUNCTIONS = (
    "radians",
    "degrees",
    "sin",
    "cos",
    "tan",
    "asin",
    "acos",
    "atan",
    "sinh",
    "cosh",
    "tanh",
    "asinh",
    "acosh",
    "atanh",

    "pow",
    "exp",
    "exp2",
    "log",
    "log2",
    "sqrt",
    "inversesqrt",
    "abs",
    "sign",
    "floor",
    "round",
    "roundEven",
    "trunc",
    "ceil",
    "fract",
    "mod",
    "modf",
    "min",
    "max",
    "clamp",
    "mix",
    "fma",
    "step",
    "smoothstep",
    "isnan",
    "isinf",
    "floatBitsToInt",
    "floatBitsToUint",
    "intBitsToFloat",
    "uintBitsToFloat",

    "length",
    "distance",
    "dot",
    "cross",
    "normalize",
    "reflect",
    "refract",
    "faceforward",
    "matrixCompMult",
    "outerProduct",
    "transpose",
    "determinant",
    "inverse",

    "lessThan",
    "greaterThan",
    "lessThanEqual",
    "greaterThanEqual",
    "equal",
    "notEqual",
    "any",
    "all",
    "not",

    "textureSize",
    "textureQueryLod",
    "textureQueryLevels",
    "texture",
    "textureProj",
    "textureLod",
    "textureProjLod",
    "textureProjGrad",
    "texelFetch",
    "dFdx",
    "dFdxCoarse",
    "dFdxFine",
    "dFdy",
    "dFdyCoarse",
    "dFdyFine",
    "fwidth",
    "fwidthCoarse",
    "fwidthFine",

    "packHalf2x16",
    "unpackHalf2x16",
    "packUnorm2x16",
    "unpackUnorm2x16",
    "packSnorm2x16",
    "unpackSnorm2x16",
    "packUnorm4x8",
    "unpackUnorm4x8",
    "packSnorm4x8",
    "unpackSnorm4x8",

    "bitfieldExtract",
    "bitfieldInsert",
    "bitfieldReverse",
    "bitCount",
    "findLSB",
    "findMSB",
    "imulExtended",
    "umulExtended",
    "uaddCarry",
    "usubBorrow",
    "idexp",
    "frexp",
)

class GDShaderLexer(GLShaderLexer):
    name = "GDShader"
    aliases = ["gdshader"]
    filenames = ["*.gdshader"]

    tokens = {
        "root": [
            # (words(BUILT_IN_SPATIAL_GLOBAL, prefix=r"\b", suffix=r"\b"), Name.Variable),
            # (words(BUILT_IN_SPATIAL_VERTEX, prefix=r"\b", suffix=r"\b"), Name.Variable),
            # (words(BUILT_IN_SPATIAL_FRAGMENT, prefix=r"\b", suffix=r"\b"), Name.Variable),
            # (words(BUILT_IN_SPATIAL_LIGHT, prefix=r"\b", suffix=r"\b"), Name.Variable),
            # We are not keeping track of a whole list. It would tend to be out-of-date.
            # The following is less reliable, but it's okay for the docs.
            # Assume that anything in uppercase is a built-in variable.
            (r"\b[A-Z][A-Z_0-9]+\b", Name.Variable),
            (r"render_mode\s+", Keyword, "mode_list"),
            (r"stencil_mode\s+", Keyword, "mode_list"),
            (words(KEYWORDS, prefix=r"\b", suffix=r"\b"), Keyword),
            (words(KEYWORDS_CONTROL_FLOW, prefix=r"\b", suffix=r"\b"), Keyword.ControlFlow),
            (words(BUILT_IN_FUNCTIONS, prefix=r"\b", suffix=r"\b"), Keyword),
            # Anything after a dot is a component.
            (r"(?<!\.)(\.)([a-zA-Z_]\w*)\b(?!\s*\()", bygroups(Operator, Name.Variable.Instance)),
            (r"/(\\\n)?\*\*(.|\n)*?\*(\\\n)?/", Comment.Doc),
            # Function declaration.
            (r"\w+(?=\([\w\s,]*\)\s*{)", Name.Function),
            (r"\"", String, "string"),
            # Preprocessor directive.
            (r"(#)(\w+)", bygroups(Operator, Keyword.ControlFlow)),
            inherit
        ],
        "mode_list": [
             # We are not keeping track of a whole list, as it's prone to be out-of-date.
            (r"\w+", Name.Class),
            (r"\s+", Whitespace),
            (r",", Operator),
            (r";", Operator, "#pop"),
        ],
        "string": [
            (r"\"", String.Double, "#pop"),
            (r"\\\\|\\\"|\\\n", String.Escape),
            (r"[^\\\'\"%\n]+", String),
            (r"[\'\"\\]", String),
        ]
    }

def setup(sphinx):
    from sphinx.highlighting import lexers

    sphinx.add_lexer("gdshader", GDShaderLexer)
    lexers["gdshader"] = GDShaderLexer()

    return {
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
